tls_server_config:
  cert_file: "/tmp/nginx-exporter.crt"
  key_file: "/tmp/nginx-exporter.key"
  client_auth_type: "RequireAndVerifyClientCert"
  client_ca_file: "/tmp/ca.crt"
  client_allowed_sans: ["10.0.4.1","10.0.3.1"]
